export class Data {

  data: any[] = [
    {
      _id: "5daed0085e6105e7455ec527",
      index: 0,
      guid: "6e5ca780-d521-407d-b16d-f41aaeeaf4d4",
      isActive: false,
      balance: "$1,037.26",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "green",
      name: "Miranda Fletcher",
      gender: "female",
      company: "KRAG",
      email: "mirandafletcher@krag.com",
      phone: "+1 (873) 485-3746",
      address: "327 Waldorf Court, Goldfield, Georgia, 2257",
      isAdmin: true,
      nicNumber: "919598060V",
      height: 215.35,
      weight: 191.25,
      bloodGroup: "b",
      latitude: 39.134314,
      longitude: -36.767995,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "right",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 1,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "bluma",
      cssFramworkGrade: 2,
      prefuxTool: "figma",
      prefuxToolGrade: 3,
      prefDb: "mySql",
      dbRating: 5,
      overallGrade: "63%",
      reviewerOneRating: "52%",
      reviewerTwoRating: "79%",
      reviewerThreeRating: "95%",
      isQualified: true
    },
    {
      _id: "5daed008f856b220940a569c",
      index: 1,
      guid: "19d3ed48-9680-40d0-bd65-64a704b95249",
      isActive: false,
      balance: "$3,543.88",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "green",
      name: "Essie Warren",
      gender: "female",
      company: "GINKLE",
      email: "essiewarren@ginkle.com",
      phone: "+1 (802) 559-2284",
      address: "138 Farragut Road, Robbins, New York, 1699",
      isAdmin: false,
      nicNumber: "3673552426V",
      height: 281.86,
      weight: 77.49,
      bloodGroup: "o",
      latitude: -45.34603,
      longitude: 40.549096,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "left",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 2,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 5,
      prefferedCssFramework: "pureCss",
      cssFramworkGrade: 5,
      prefuxTool: "inVision",
      prefuxToolGrade: 2,
      prefDb: "msSql",
      dbRating: 2,
      overallGrade: "34%",
      reviewerOneRating: "23%",
      reviewerTwoRating: "38%",
      reviewerThreeRating: "88%",
      isQualified: false
    },
    {
      _id: "5daed008ba7778a9d3d27588",
      index: 2,
      guid: "1fa31d6a-7840-47e3-9308-a8e2f93ba6af",
      isActive: true,
      balance: "$1,906.60",
      picture: "http://placehold.it/32x32",
      age: 24,
      eyeColor: "green",
      name: "Yesenia Mcgee",
      gender: "female",
      company: "AQUAZURE",
      email: "yeseniamcgee@aquazure.com",
      phone: "+1 (894) 411-2925",
      address: "549 Blake Avenue, Ventress, Palau, 307",
      isAdmin: true,
      nicNumber: "9963680642V",
      height: 281.05,
      weight: 192.37,
      bloodGroup: "ab",
      latitude: 48.106554,
      longitude: 157.053793,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 3,
      prefferedFrontEndFramework: "angular",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "kendo",
      cssFramworkGrade: 4,
      prefuxTool: "figma",
      prefuxToolGrade: 5,
      prefDb: "msSql",
      dbRating: 3,
      overallGrade: "11%",
      reviewerOneRating: "21%",
      reviewerTwoRating: "27%",
      reviewerThreeRating: "19%",
      isQualified: true
    },
    {
      _id: "5daed0087d6c888a5f8d44f1",
      index: 3,
      guid: "afcc1b23-37e4-4840-937c-985bcebd8878",
      isActive: true,
      balance: "$2,896.05",
      picture: "http://placehold.it/32x32",
      age: 20,
      eyeColor: "brown",
      name: "Riley Mayo",
      gender: "male",
      company: "ZORROMOP",
      email: "rileymayo@zorromop.com",
      phone: "+1 (915) 440-3907",
      address: "332 Meadow Street, Camino, Oregon, 8075",
      isAdmin: true,
      nicNumber: "7822748076V",
      height: 223.48,
      weight: 81.1,
      bloodGroup: "a",
      latitude: -19.778385,
      longitude: 6.261469,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "left",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 3,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "material",
      cssFramworkGrade: 4,
      prefuxTool: "Framer X",
      prefuxToolGrade: 2,
      prefDb: "msSql",
      dbRating: 5,
      overallGrade: "85%",
      reviewerOneRating: "6%",
      reviewerTwoRating: "5%",
      reviewerThreeRating: "91%",
      isQualified: false
    },
    {
      _id: "5daed0087744c4ac3f70b48a",
      index: 4,
      guid: "016d5e98-c531-4321-9844-4fd3399ca73b",
      isActive: false,
      balance: "$1,447.12",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "brown",
      name: "Juarez Kane",
      gender: "male",
      company: "OBLIQ",
      email: "juarezkane@obliq.com",
      phone: "+1 (959) 459-2826",
      address: "708 Dictum Court, Warsaw, South Carolina, 5361",
      isAdmin: true,
      nicNumber: "3100829484V",
      height: 228.19,
      weight: 63.14,
      bloodGroup: "a",
      latitude: -80.708808,
      longitude: -123.167973,
      prefferedFoot: "left",
      battingHand: "left",
      bowlingHand: "right",
      proficientLanguage: "spanish",
      prefferedProgrammingLanguage: "c",
      progLangGrade: 1,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 4,
      prefferedCssFramework: "bluma",
      cssFramworkGrade: 2,
      prefuxTool: "Framer X",
      prefuxToolGrade: 5,
      prefDb: "mySql",
      dbRating: 5,
      overallGrade: "6%",
      reviewerOneRating: "27%",
      reviewerTwoRating: "33%",
      reviewerThreeRating: "62%",
      isQualified: true
    },
    {
      _id: "5daed008fd9e9c87133e0723",
      index: 5,
      guid: "022f6c08-fdeb-4565-b6d7-20fa555d5fec",
      isActive: false,
      balance: "$2,561.10",
      picture: "http://placehold.it/32x32",
      age: 25,
      eyeColor: "green",
      name: "Booker Mosley",
      gender: "male",
      company: "COMFIRM",
      email: "bookermosley@comfirm.com",
      phone: "+1 (883) 438-2150",
      address: "991 Whitty Lane, Onton, Kansas, 3375",
      isAdmin: true,
      nicNumber: "6697811345V",
      height: 116.1,
      weight: 190.06,
      bloodGroup: "b",
      latitude: -60.209979,
      longitude: 21.36724,
      prefferedFoot: "left",
      battingHand: "left",
      bowlingHand: "right",
      proficientLanguage: "spanish",
      prefferedProgrammingLanguage: "js",
      progLangGrade: 5,
      prefferedFrontEndFramework: "vue",
      frontendFramworkGrade: 5,
      prefferedCssFramework: "kendo",
      cssFramworkGrade: 4,
      prefuxTool: "inVision",
      prefuxToolGrade: 3,
      prefDb: "mongo",
      dbRating: 1,
      overallGrade: "15%",
      reviewerOneRating: "14%",
      reviewerTwoRating: "14%",
      reviewerThreeRating: "46%",
      isQualified: true
    },
    {
      _id: "5daed00824ff2befcb6dfe4e",
      index: 6,
      guid: "2e4b933e-eb3e-46ad-941d-6b0e2e497641",
      isActive: true,
      balance: "$3,465.06",
      picture: "http://placehold.it/32x32",
      age: 39,
      eyeColor: "green",
      name: "Mable Atkins",
      gender: "female",
      company: "POOCHIES",
      email: "mableatkins@poochies.com",
      phone: "+1 (866) 483-3802",
      address: "177 Exeter Street, Convent, Indiana, 3930",
      isAdmin: true,
      nicNumber: "2338296975V",
      height: 191.39,
      weight: 98.63,
      bloodGroup: "ab",
      latitude: -83.479596,
      longitude: 141.869904,
      prefferedFoot: "left",
      battingHand: "left",
      bowlingHand: "right",
      proficientLanguage: "french",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 4,
      prefferedFrontEndFramework: "vue",
      frontendFramworkGrade: 5,
      prefferedCssFramework: "material",
      cssFramworkGrade: 2,
      prefuxTool: "inVision",
      prefuxToolGrade: 5,
      prefDb: "msSql",
      dbRating: 4,
      overallGrade: "50%",
      reviewerOneRating: "69%",
      reviewerTwoRating: "49%",
      reviewerThreeRating: "34%",
      isQualified: true
    },
    {
      _id: "5daed0083279db1a8de7a89e",
      index: 7,
      guid: "503d4b71-ee30-4316-b49c-f4e04030ad67",
      isActive: true,
      balance: "$1,853.37",
      picture: "http://placehold.it/32x32",
      age: 20,
      eyeColor: "blue",
      name: "David French",
      gender: "male",
      company: "ERSUM",
      email: "davidfrench@ersum.com",
      phone: "+1 (856) 582-2055",
      address: "603 Brevoort Place, Bentley, Virgin Islands, 2099",
      isAdmin: false,
      nicNumber: "9314633533V",
      height: 102.32,
      weight: 191.46,
      bloodGroup: "a",
      latitude: 86.098743,
      longitude: -78.865506,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "c",
      progLangGrade: 5,
      prefferedFrontEndFramework: "angular",
      frontendFramworkGrade: 2,
      prefferedCssFramework: "bluma",
      cssFramworkGrade: 3,
      prefuxTool: "Framer X",
      prefuxToolGrade: 4,
      prefDb: "mongo",
      dbRating: 4,
      overallGrade: "82%",
      reviewerOneRating: "78%",
      reviewerTwoRating: "52%",
      reviewerThreeRating: "10%",
      isQualified: false
    },
    {
      _id: "5daed00832ae8172bca83200",
      index: 8,
      guid: "d5a892f5-bec6-45d4-ba89-eb4aea231fbd",
      isActive: false,
      balance: "$1,925.11",
      picture: "http://placehold.it/32x32",
      age: 32,
      eyeColor: "green",
      name: "Sonya Fuentes",
      gender: "female",
      company: "OBONES",
      email: "sonyafuentes@obones.com",
      phone: "+1 (876) 593-3521",
      address: "514 Tech Place, Axis, Maine, 4879",
      isAdmin: false,
      nicNumber: "5923434378V",
      height: 243.06,
      weight: 53.17,
      bloodGroup: "ab",
      latitude: -42.345194,
      longitude: 160.46794,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 3,
      prefferedFrontEndFramework: "vue",
      frontendFramworkGrade: 2,
      prefferedCssFramework: "bootstrap",
      cssFramworkGrade: 1,
      prefuxTool: "inVision",
      prefuxToolGrade: 5,
      prefDb: "msSql",
      dbRating: 3,
      overallGrade: "9%",
      reviewerOneRating: "78%",
      reviewerTwoRating: "79%",
      reviewerThreeRating: "38%",
      isQualified: false
    },
    {
      _id: "5daed0084925f3028350c5ca",
      index: 9,
      guid: "9e5b6ca7-80cb-4eb1-933d-b0042231bddd",
      isActive: true,
      balance: "$1,457.23",
      picture: "http://placehold.it/32x32",
      age: 40,
      eyeColor: "green",
      name: "Fuller Solomon",
      gender: "male",
      company: "GINKOGENE",
      email: "fullersolomon@ginkogene.com",
      phone: "+1 (852) 502-3610",
      address: "470 Nevins Street, Whitestone, Texas, 9411",
      isAdmin: true,
      nicNumber: "1515865384V",
      height: 120.33,
      weight: 197.91,
      bloodGroup: "ab",
      latitude: -42.443768,
      longitude: -115.672827,
      prefferedFoot: "left",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 4,
      prefferedFrontEndFramework: "angular",
      frontendFramworkGrade: 1,
      prefferedCssFramework: "pureCss",
      cssFramworkGrade: 4,
      prefuxTool: "inVision",
      prefuxToolGrade: 3,
      prefDb: "mySql",
      dbRating: 4,
      overallGrade: "24%",
      reviewerOneRating: "94%",
      reviewerTwoRating: "20%",
      reviewerThreeRating: "90%",
      isQualified: false
    },
    {
      _id: "5daed008048726c0b385e097",
      index: 10,
      guid: "b861f5dd-fffe-486f-b20c-84e589249631",
      isActive: true,
      balance: "$1,863.88",
      picture: "http://placehold.it/32x32",
      age: 26,
      eyeColor: "blue",
      name: "Dee Savage",
      gender: "female",
      company: "COSMETEX",
      email: "deesavage@cosmetex.com",
      phone: "+1 (904) 425-2708",
      address: "504 Berry Street, Beason, Louisiana, 3546",
      isAdmin: true,
      nicNumber: "197832228V",
      height: 258.6,
      weight: 77.07,
      bloodGroup: "b",
      latitude: -71.915597,
      longitude: 42.740116,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "french",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 5,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 2,
      prefferedCssFramework: "pureCss",
      cssFramworkGrade: 4,
      prefuxTool: "Framer X",
      prefuxToolGrade: 1,
      prefDb: "mongo",
      dbRating: 1,
      overallGrade: "51%",
      reviewerOneRating: "14%",
      reviewerTwoRating: "17%",
      reviewerThreeRating: "5%",
      isQualified: false
    },
    {
      _id: "5daed008e907c73a229e214d",
      index: 11,
      guid: "706653a0-c477-431b-8d95-fc6c3344d6ba",
      isActive: false,
      balance: "$1,006.02",
      picture: "http://placehold.it/32x32",
      age: 34,
      eyeColor: "brown",
      name: "Liz Meyers",
      gender: "female",
      company: "KIDSTOCK",
      email: "lizmeyers@kidstock.com",
      phone: "+1 (869) 514-2858",
      address: "847 Applegate Court, Hiseville, Arkansas, 9638",
      isAdmin: true,
      nicNumber: "4167061315V",
      height: 221.01,
      weight: 97.16,
      bloodGroup: "a",
      latitude: -41.63711,
      longitude: 43.972171,
      prefferedFoot: "left",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "spanish",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 1,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "material",
      cssFramworkGrade: 2,
      prefuxTool: "adobeXd",
      prefuxToolGrade: 1,
      prefDb: "mySql",
      dbRating: 3,
      overallGrade: "50%",
      reviewerOneRating: "43%",
      reviewerTwoRating: "22%",
      reviewerThreeRating: "32%",
      isQualified: false
    },
    {
      _id: "5daed008ab1e8c2c14210f42",
      index: 12,
      guid: "e18b45c7-399c-4064-ab19-ef79034ed86c",
      isActive: false,
      balance: "$1,071.11",
      picture: "http://placehold.it/32x32",
      age: 21,
      eyeColor: "brown",
      name: "Bradford Carver",
      gender: "male",
      company: "ZERBINA",
      email: "bradfordcarver@zerbina.com",
      phone: "+1 (848) 426-2760",
      address: "111 John Street, Kirk, Illinois, 3688",
      isAdmin: true,
      nicNumber: "4527084566V",
      height: 101.94,
      weight: 154.89,
      bloodGroup: "ab",
      latitude: 54.414743,
      longitude: -33.545471,
      prefferedFoot: "left",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 1,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "material",
      cssFramworkGrade: 1,
      prefuxTool: "Framer X",
      prefuxToolGrade: 3,
      prefDb: "mongo",
      dbRating: 5,
      overallGrade: "89%",
      reviewerOneRating: "91%",
      reviewerTwoRating: "4%",
      reviewerThreeRating: "9%",
      isQualified: false
    },
    {
      _id: "5daed00821a7a721c11ba172",
      index: 13,
      guid: "777cfc65-807b-4d18-bbda-a5608ce92f46",
      isActive: false,
      balance: "$2,749.93",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "brown",
      name: "Chaney Bernard",
      gender: "male",
      company: "BULLJUICE",
      email: "chaneybernard@bulljuice.com",
      phone: "+1 (949) 454-3576",
      address:
        "669 Fulton Street, Chamberino, Federated States Of Micronesia, 3674",
      isAdmin: false,
      nicNumber: "1869647956V",
      height: 164.11,
      weight: 164.69,
      bloodGroup: "a",
      latitude: 77.937531,
      longitude: 44.645666,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "french",
      prefferedProgrammingLanguage: "c#",
      progLangGrade: 4,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "bootstrap",
      cssFramworkGrade: 4,
      prefuxTool: "adobeXd",
      prefuxToolGrade: 4,
      prefDb: "mongo",
      dbRating: 2,
      overallGrade: "89%",
      reviewerOneRating: "43%",
      reviewerTwoRating: "82%",
      reviewerThreeRating: "79%",
      isQualified: true
    },
    {
      _id: "5daed0089b97d6e85dd350da",
      index: 14,
      guid: "848a0ca7-f67c-40b0-9206-14b23de4eb01",
      isActive: false,
      balance: "$1,211.23",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "brown",
      name: "Short Kidd",
      gender: "male",
      company: "COWTOWN",
      email: "shortkidd@cowtown.com",
      phone: "+1 (968) 524-3257",
      address: "790 Rewe Street, Monument, Hawaii, 7883",
      isAdmin: true,
      nicNumber: "2473810258V",
      height: 111.29,
      weight: 87.93,
      bloodGroup: "ab",
      latitude: 19.285368,
      longitude: -122.334862,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "c",
      progLangGrade: 5,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 2,
      prefferedCssFramework: "material",
      cssFramworkGrade: 3,
      prefuxTool: "figma",
      prefuxToolGrade: 4,
      prefDb: "mongo",
      dbRating: 4,
      overallGrade: "2%",
      reviewerOneRating: "53%",
      reviewerTwoRating: "30%",
      reviewerThreeRating: "28%",
      isQualified: true
    },
    {
      _id: "5daed008146d900708c93ed4",
      index: 15,
      guid: "a9c32a6c-545b-456d-8a26-536371dfab87",
      isActive: true,
      balance: "$2,065.55",
      picture: "http://placehold.it/32x32",
      age: 22,
      eyeColor: "green",
      name: "Raymond Delacruz",
      gender: "male",
      company: "SPRINGBEE",
      email: "raymonddelacruz@springbee.com",
      phone: "+1 (932) 420-3688",
      address: "576 Rodney Street, Lopezo, Delaware, 4381",
      isAdmin: false,
      nicNumber: "9182488769V",
      height: 237.42,
      weight: 178.8,
      bloodGroup: "a",
      latitude: 66.184993,
      longitude: 103.622625,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "left",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "c",
      progLangGrade: 2,
      prefferedFrontEndFramework: "vue",
      frontendFramworkGrade: 4,
      prefferedCssFramework: "bluma",
      cssFramworkGrade: 5,
      prefuxTool: "UX Pin",
      prefuxToolGrade: 4,
      prefDb: "mongo",
      dbRating: 1,
      overallGrade: "91%",
      reviewerOneRating: "11%",
      reviewerTwoRating: "56%",
      reviewerThreeRating: "13%",
      isQualified: false
    },
    {
      _id: "5daed00841f12ebc3970fa6e",
      index: 16,
      guid: "35ca6d9f-7103-4f09-aa05-3950bb4401ba",
      isActive: false,
      balance: "$1,515.26",
      picture: "http://placehold.it/32x32",
      age: 34,
      eyeColor: "green",
      name: "Ester Wolf",
      gender: "female",
      company: "GEOLOGIX",
      email: "esterwolf@geologix.com",
      phone: "+1 (846) 532-3333",
      address: "574 Batchelder Street, Tibbie, American Samoa, 1010",
      isAdmin: true,
      nicNumber: "353059545V",
      height: 221.05,
      weight: 161.16,
      bloodGroup: "a",
      latitude: -86.783549,
      longitude: -94.299257,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "right",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "c",
      progLangGrade: 4,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 4,
      prefferedCssFramework: "material",
      cssFramworkGrade: 3,
      prefuxTool: "Framer X",
      prefuxToolGrade: 3,
      prefDb: "mongo",
      dbRating: 3,
      overallGrade: "28%",
      reviewerOneRating: "23%",
      reviewerTwoRating: "100%",
      reviewerThreeRating: "82%",
      isQualified: true
    },
    {
      _id: "5daed008817e5a354da39a42",
      index: 17,
      guid: "50128443-b2b9-40e4-a623-64f87c760565",
      isActive: true,
      balance: "$3,828.69",
      picture: "http://placehold.it/32x32",
      age: 36,
      eyeColor: "green",
      name: "Slater Vasquez",
      gender: "male",
      company: "ENQUILITY",
      email: "slatervasquez@enquility.com",
      phone: "+1 (926) 433-3595",
      address: "213 Karweg Place, Tuttle, Iowa, 8343",
      isAdmin: true,
      nicNumber: "4267028949V",
      height: 231.34,
      weight: 140.65,
      bloodGroup: "b",
      latitude: -69.892257,
      longitude: -103.283228,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "python",
      progLangGrade: 4,
      prefferedFrontEndFramework: "angular",
      frontendFramworkGrade: 3,
      prefferedCssFramework: "pureCss",
      cssFramworkGrade: 2,
      prefuxTool: "adobeXd",
      prefuxToolGrade: 4,
      prefDb: "mySql",
      dbRating: 3,
      overallGrade: "57%",
      reviewerOneRating: "97%",
      reviewerTwoRating: "72%",
      reviewerThreeRating: "94%",
      isQualified: true
    },
    {
      _id: "5daed00888a4d139e56a25f9",
      index: 18,
      guid: "e36e841e-2d6d-4be9-a1b6-534052488545",
      isActive: true,
      balance: "$2,810.22",
      picture: "http://placehold.it/32x32",
      age: 32,
      eyeColor: "brown",
      name: "Leona Norris",
      gender: "female",
      company: "BESTO",
      email: "leonanorris@besto.com",
      phone: "+1 (818) 580-2732",
      address: "651 Canda Avenue, Delco, Florida, 414",
      isAdmin: true,
      nicNumber: "7401857519V",
      height: 149.2,
      weight: 92.45,
      bloodGroup: "o",
      latitude: 8.229232,
      longitude: -62.188065,
      prefferedFoot: "right",
      battingHand: "right",
      bowlingHand: "left",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "c#",
      progLangGrade: 1,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 1,
      prefferedCssFramework: "bluma",
      cssFramworkGrade: 5,
      prefuxTool: "figma",
      prefuxToolGrade: 3,
      prefDb: "mongo",
      dbRating: 2,
      overallGrade: "52%",
      reviewerOneRating: "25%",
      reviewerTwoRating: "84%",
      reviewerThreeRating: "25%",
      isQualified: true
    },
    {
      _id: "5daed008d302a963847475f1",
      index: 19,
      guid: "6c17a982-f983-4208-9711-b817309ffd94",
      isActive: false,
      balance: "$2,172.15",
      picture: "http://placehold.it/32x32",
      age: 34,
      eyeColor: "brown",
      name: "Ayers Alexander",
      gender: "male",
      company: "MEDIFAX",
      email: "ayersalexander@medifax.com",
      phone: "+1 (867) 408-2614",
      address: "793 Doscher Street, Kipp, Massachusetts, 8460",
      isAdmin: true,
      nicNumber: "686588612V",
      height: 221.94,
      weight: 183.06,
      bloodGroup: "ab",
      latitude: 81.881997,
      longitude: -110.472581,
      prefferedFoot: "right",
      battingHand: "left",
      bowlingHand: "left",
      proficientLanguage: "chinese",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 3,
      prefferedFrontEndFramework: "react",
      frontendFramworkGrade: 5,
      prefferedCssFramework: "kendo",
      cssFramworkGrade: 5,
      prefuxTool: "inVision",
      prefuxToolGrade: 1,
      prefDb: "mySql",
      dbRating: 2,
      overallGrade: "87%",
      reviewerOneRating: "36%",
      reviewerTwoRating: "36%",
      reviewerThreeRating: "20%",
      isQualified: true
    },
    {
      _id: "5daed008f87c845861f1028e",
      index: 20,
      guid: "003faede-758a-4410-8fd7-9217e5552985",
      isActive: false,
      balance: "$2,068.22",
      picture: "http://placehold.it/32x32",
      age: 39,
      eyeColor: "green",
      name: "Walton Nunez",
      gender: "male",
      company: "KNOWLYSIS",
      email: "waltonnunez@knowlysis.com",
      phone: "+1 (962) 467-3792",
      address: "273 Rockwell Place, Naomi, Oklahoma, 5710",
      isAdmin: true,
      nicNumber: "7586086895V",
      height: 139.04,
      weight: 72.52,
      bloodGroup: "ab",
      latitude: -23.674573,
      longitude: -51.442301,
      prefferedFoot: "left",
      battingHand: "right",
      bowlingHand: "right",
      proficientLanguage: "english",
      prefferedProgrammingLanguage: "c++",
      progLangGrade: 4,
      prefferedFrontEndFramework: "vue",
      frontendFramworkGrade: 4,
      prefferedCssFramework: "material",
      cssFramworkGrade: 1,
      prefuxTool: "UX Pin",
      prefuxToolGrade: 3,
      prefDb: "mongo",
      dbRating: 1,
      overallGrade: "26%",
      reviewerOneRating: "3%",
      reviewerTwoRating: "47%",
      reviewerThreeRating: "93%",
      isQualified: true
    }
  ];

  constructor() {}

  get getData() {
    return this.data;
  }
}
